### ISSUE TITLE
how can use this project to remove image watermarks

### ISSUE THREAD

**Issue by shinebay** [adamstseng/general-deep-image-completion#3]
Very nice projects, I want to use this to remove watermarks in some photo stock websites, for example:
![image](https://user-images.githubusercontent.com/7820385/40163940-c2617a92-59ea-11e8-849e-49ac6083801b.png)
how can I remove watermark on this image? thank you:)

**Comment by chingweitseng** [comment]
After following the setup for our demo system, you can put this example image into **general-image-completion/testimages** folder, and run the **demo.py** to scribble out the unwanted region in the image. :D
